server:
  port: 10000

spring:
  application:
    name: configserver
  profiles:
    active: native
    include: @profileActive@
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/