spring:
  application:
    name: config-server
  profiles:
    active: native
    include: @profileActive@
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/