# 网关配置
zuul:
  prefix: /api
  routes:
    # 微服务集群内通过serviceId查找
    demo-a:
      path: /a/**
      serviceId: client-demo-a-dist
      sensitive-headers:
    demo-b:
      path: /b/**
      serviceId: client-demo-b-dist
      sensitive-headers:
    # 外部服务通过url跳转
    boxuegu:
      path: /bxg/**
      url: http://211.103.142.26:5881

# 配置用于传递对应的oauth验证信息
# 需要在对应的route service中加上“sensitive-headers:”空参数来允许请求传递“authorization”请求头
proxy:
  auth:
    routes:
      demo-a: oauth2

swagger:
  enabled: true
  title: gateway接口文档
  description: gateway接口文档描述
  contact:
    name: 张晓峰
    url: https://leonzhangxf.com
    email: leonzhangxf@gmail.com