# 网关配置
zuul:
  prefix: /api
  routes:
    demo-a:
      path: /a/**
      serviceId: client-demo-a-dist
    demo-b:
      path: /b/**
      serviceId: client-demo-b-dist
    boxuegu:
      path: /bxg/**
      url: http://211.103.142.26:5881

swagger:
  enabled: true
  title: gateway接口文档
  description: gateway接口文档描述
  contact:
    name: 张晓峰
    url: https://leonzhangxf.com
    email: leonzhangxf@gmail.com